name: connection_verify
description: Package to verify the network connection status, it allows to knows how is the network connection status, for Android and iOS, 'true' if is connected, 'false' if is not.
version: 1.0.5

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2

flutter:
